# An Introduction to Pandas

## Basic Pandas Concepts

Some very basic Pandas and python concepts to get started

#### Import the pandas package

In [83]:
import pandas as pd

#### Create a simple DataFrame

- syntax: pd.DataFrame({column1 : value1, column2 : value2, column3 : value3})

You can have anything as column names and anything as values.

The only requirement is to have all value lists being of equal length

In [84]:
df = pd.DataFrame({'name':['Bob','Jen','Tim'],
                   'age':[20,30,40],
                   'pet':['cat', 'dog', 'bird']})

df

  name  age   pet
0  Bob   20   cat
1  Jen   30   dog
2  Tim   40  bird

In [85]:
# initialize list of lists
data = [['Bob', 20,'cat'], ['Jen', 30,'dog'], ['Tim', 40,'bird']]

# Create the pandas DataFrame
df = pd.DataFrame(data, columns=['name', 'age','pet'])
df

  name  age   pet
0  Bob   20   cat
1  Jen   30   dog
2  Tim   40  bird

#### View the column names and index values

The index is one of the most important concepts in pandas.

Each dataframe has only a single index which is always available as `df.index` and if you do not supply one  a new one is made automatically.

Indexes define how to access rows of the dataframe.

The simplest index is the range index but there are more complex ones like interval index, datetime index and multi index.

In [86]:
print(df.columns)
print(df.index)

Index(['name', 'age', 'pet'], dtype='object')
RangeIndex(start=0, stop=3, step=1)

#### Select a column by name in 2 different ways

These two ways are equivalent and can be used interchangeably almost always.

The primary exception is when the name of the column contains spaces. If for example we had a column called "weekly sales" we have to use df['weekly sales'] because `df.weekly sales` is a syntactic error.

In [87]:
print(df['name'])
print(df.name)

0    Bob
1    Jen
2    Tim
Name: name, dtype: object
0    Bob
1    Jen
2    Tim
Name: name, dtype: object

#### Select multiple columns

To select multiple columns we use `df[columns_to_select]` where `columns_to_select` are the columns we are interested in given as a simple python list. As the result we will get another data frame.

This is the equivalent of listing columns names in `SELECT` part of a sql query.

In [88]:
df[['name','pet']]

  name   pet
0  Bob   cat
1  Jen   dog
2  Tim  bird

#### Select a row by index

Regular selection of rows goes via its index. When using range indices we can access rows using integer indices but this will not work when using datetime index for example.

We can always access any row in the dataframe using `.iloc[i]` for some integer i.

The result is a series object from which we can access values by using column indexing.

In [89]:
df.iloc[0]

name    Bob
age      20
pet     cat
Name: 0, dtype: object

### Sort Function


#### Sort the data by pet

There are two ways to sort.
- By index
- By value

By value means sorting according to value in a column.



The parameter `ascending = True` means that we want the rows sorted in ascending order. This is the same as sql 'ASC'. To get descending order use `ascending = False`.

`inplace` is very important and you should always remember it. When `inplace=True` the dataframe is modified in place which means that no copies are made and your previous data stored in the dataframe is lost. By default inplace is always False. When it is false a copy is made of your data and that copy is sorted and returned as output.

The output of `sort_values` is always a dataframe returned but the behaviour depends strongly on the `inplace` parameter.

In [90]:
df.sort_values('pet',inplace=True, ascending=True)

### Indexing with DataFrames

Everything we discussed about indexing in numpy arrays applies to dataframes as well.

DataFrames are very similar to 2d-arrays with the main exception being that in DataFrames you can index using strings (column names).

#### View the index after the sort

In [91]:
df

  name  age   pet
2  Tim   40  bird
0  Bob   20   cat
1  Jen   30   dog

#### Difference between loc and iloc

- `.loc` selection is based on the value of the index. For example if the index was categorical we could index via some category.
- `.iloc` selection is **always** based on integer positions. When using iloc we are treating the dataframe as 2d-array with no special structure compared to the case of `.loc`

In [92]:
df.loc[0] #index based

name    Bob
age      20
pet     cat
Name: 0, dtype: object

In [93]:
df.iloc[0] #relative position based indexing

name     Tim
age       40
pet     bird
Name: 2, dtype: object

#### Use iloc to select all rows of a column

This will select all rows of the second column.

Remember `:` = `::1`

First index is always row and second is always column when dealing with dataframes.

In [94]:
df.iloc[:,2]

2    bird
0     cat
1     dog
Name: pet, dtype: object

#### Use iloc to select the last row

In [95]:
df.iloc[-1,:]

name    Jen
age      30
pet     dog
Name: 1, dtype: object

## Basic Pandas Concept Exercises

In [96]:
customer_name = ['Paul','Marc','Helene','Adele','Theo']
height = [182,187,175,177,189]
city = ['Paris','Toulouse','Lyon','Marseille','Bordeaux']

#### Create a DataFrame with the data above

In [97]:
df = pd.DataFrame({
    'customer_name': customer_name,
    'height': height,
    'city': city
})

#### What is the name of the first column?

In [98]:
df.columns[0]

'customer_name'

#### Sort the DataFrame by city in descending order

In [99]:
df_sorted = df.sort_values(by='city', ascending=False)
df_sorted

  customer_name  height       city
1          Marc     187   Toulouse
0          Paul     182      Paris
3         Adele     177  Marseille
2        Helene     175       Lyon
4          Theo     189   Bordeaux

#### Which customer is in the last row of the DataFrame?

In [100]:
df_sorted.customer_name.iloc[-1]

'Theo'

#### Reorder the columns with city in the first column

In [101]:
df_reordered = df_sorted[['city','customer_name', 'height']]
df_reordered

        city customer_name  height
1   Toulouse          Marc     187
0      Paris          Paul     182
3  Marseille         Adele     177
2       Lyon        Helene     175
4   Bordeaux          Theo     189

#### Download Titanic dataset

In [102]:
import seaborn as sns

# We will use the 'titanic' dataset for real-world demographics
df = sns.load_dataset("titanic")

#### Investigate the first few rows of data

The `head` method by default prints the first 5 rows of your dataframe.

If you pass it a parameter `n` it will print first `n` rows.

In [103]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

#### Investigate the last 10 rows of data

tail is similar to head except it prints the last `n` rows.

In [104]:
df.tail(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True


## Variable Types & Levels of Measurement

Please complete this table.

| Column         | Variable Type | Sub-Type            | Measurement Level | Values |
|----------------|----------------|---------------------|-------------------|-------|
| `survived`     | Categorical    | Binary              | Nominal           | 0 = No, 1 = Yes |
| `pclass`       | Categorical    | Ordinal             | Ordinal           | 1st > 2nd > 3rd class |
| `sex`          | Categorical    | Nominal             | Nominal           | male / female |
| `age`          | Numerical      | Continuous          | Ratio             | Years |
| `sibsp`        | Numerical      | Discrete            | Ratio             | Siblings/spouses aboard |
| `parch`        | Numerical      | Discrete            | Ratio             | Parents/children aboard |
| `fare`         | Numerical      | Continuous          | Ratio             | Fare paid |
| `embarked`     | Categorical    | Nominal             | Nominal           | C, Q, S |
| `class`        | Categorical    | Ordinal             | Ordinal           | 1st, 2nd, 3rd (text) |
| `who`          | Categorical    | Nominal             | Nominal           | man, woman, child |
| `adult_male`   | Categorical    | Binary              | Nominal           | True / False |
| `deck`         | Categorical    | Nominal             | Nominal           | Deck letter |
| `embark_town`  | Categorical    | Nominal             | Nominal           | Town name |
| `alive`        | Categorical    | Binary              | Nominal           | yes / no |
| `alone`        | Categorical    | Binary              | Nominal           | True / False |

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

### Filtering Dataframes

You can filter data based on the columns and values in the dataframe

#### Filter the data for men

There are two pieces of the puzzle here:
- `data.sex=='male'` will give a boolean array where True means that row has a column called sex which has value 'male'. This numpy array is called the predicate.
- data[data.sex=='male'] will give back all rows for which the predicate holds true.

The result of this filter is a dataframe with same columns as the input dataframe.

In [106]:
df[df.sex=='male']

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

#### Filter the ages for the men

Again there are two important parts:
- `data.sex=='male'` is the predicate as before
- `data.age` means taking the values for the age column, and `data.age[data.sex=='male']` means taking all ages which are related to male rows.

The result of this is pandas series **not** a dataframe.

In [107]:
df.age[df.sex=='male']

0      22.0
4      35.0
5       NaN
6      54.0
7       2.0
       ...
883    28.0
884    25.0
886    27.0
889    26.0
890    32.0
Name: age, Length: 577, dtype: float64

### Adding methods to filters

A method is a function and is used frequently when analyzing data in Pandas. There are countless Pandas methods. We'll go over a few of the basic ones to show how you can use methods to quickly analyze your data.

#### How many men and women were on the Titanic?

The pipeline always goes the same way
- Predicate is evalatued
- Data is filtered according to a predicate
- An aggregate value is computed after the filtering.

The count method simply counts the number of frames in the dataframe.

In [108]:
df.sex[df.sex=='male'].count()

np.int64(577)

In [109]:
df.sex[df.sex=='female'].count()

np.int64(314)

#### What was the survival rate for adult men (age>=18)

Here we combine predicates using the and operator (&).

This operator applies the logical and operation between elements at matching positions.

For example:
- x = np.array([True, False, True, True])
- y = np.array([False, True, False, True])
- will give x & y = np.array([True & False, False & True, True & False, True & True]).

In the following example we use the or combiner (|).

You can combine any two boolean numpy arrays as long as they have the same shape using the & and | operators.

Combining regular python lists this way does not work.

In [110]:
df.survived[(df.sex=='male')&(df.age>=18)]

0      0
4      0
6      0
12     0
13     0
      ..
883    0
884    0
886    0
889    1
890    0
Name: survived, Length: 395, dtype: int64

#### What was the survival rate for women and children?

The mean method is the same as AVERAGE in SQL.

In [111]:
df.survived[(df.sex=='female')|(df.age<18)].mean()

np.float64(0.6881720430107527)

#### Use groupby to compare the survival rates of men and women

The `groupby` method is one of the most important tools you will use in your day to day work.

It's main input parameter is either a string denoting a column name or a list of strings denoting a list of column names.

It's output is a GroupBy object which is very similar to a dataframe.

The operation of groupby is the same as SQL GROUPBY.

In [112]:
df.groupby('sex')['survived'].mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

## More Basic Pandas Exercises

#### What was the average age of the survivors?

In [113]:
avg_age_survivors = df[df['survived'] == 1]['age'].mean()
avg_age_survivors

np.float64(28.343689655172415)

#### What was the combined survival rate of both children (age less than 18) and seniors (age greater than 60)?

In [114]:
child_or_senior = df[(df['age'] < 18) | (df['age'] > 60)]
child_or_senior.survived.mean()

np.float64(0.4888888888888889)

#### Group by pClass and investigate average survival rate, age and fare

In [115]:
grouped_stats = df.groupby("pclass")[["survived", "age", "fare"]].mean().round(2)
grouped_stats

        survived    age   fare
pclass
1           0.63  38.23  84.15
2           0.47  29.88  20.66
3           0.24  25.14  13.68